name: Xcode - Build and Upload

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build using xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          TVOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.TVOS_BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          TVOS_PP_PATH=$RUNNER_TEMP/tvos_build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          echo -n "$TVOS_BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $TVOS_PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $TVOS_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install App Store Connect private key
        id: appstore-private-key
        env:
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        run: |
          PRIV_KEY_DIR="$HOME/private_keys"
          AUTH_KEY_FILE="$PRIV_KEY_DIR/AuthKey_$API_KEY_ID.p8"

          echo "::set-output name=AUTH_KEY_PATH::$AUTH_KEY_FILE"

          mkdir -p $PRIV_KEY_DIR
          echo "$API_PRIVATE_KEY" > "$AUTH_KEY_FILE"
      
      - name: Cache dependencies (Carthage)
        uses: actions/cache@v2
        id: cache-dependecies-carthage
        with:
          path: ./Carthage
          key: ${{ runner.OS }}-cache-carthage-${{ hashFiles('./Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.OS }}-cache-carthage-
      
      - name: Bootstrap (Carthage)
        if: steps.cache-dependecies-carthage.outputs.cache-hit != 'true'
        run: ./carthage.sh bootstrap --platform ios,tvos
        shell: bash
      
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependecies
        with:
          path: ./Thirdparties
          key: ${{ runner.OS }}-cache-${{ hashFiles('./bootstrap.sh') }}
          restore-keys: |
            ${{ runner.OS }}-cache-
      
      - name: Bootstrap
        if: steps.cache-dependecies.outputs.cache-hit != 'true'
        run: ./bootstrap.sh
        shell: bash
            
      - name: Bump version
        env:
          build_number: ${{ github.run_number }}
        run: xcrun agvtool new-version -all $((14+$build_number)) # temp fix

      - name: Build (iOS)
        id: build-ios
        env:
          SCHEME: ${{ 'SwiftyTorrent' }}
        run: |
          archivePath=build/$SCHEME.xcarchive

          echo "::set-output name=SCHEME::$SCHEME"

          xcodebuild clean build archive \
            -scheme "$SCHEME" \
            -archivePath "$archivePath" | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive (iOS)
        id: archive-ios
        env:
          SCHEME: ${{ steps.build-ios.outputs.SCHEME }}
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          AUTH_KEY_PATH: ${{ steps.appstore-private-key.outputs.AUTH_KEY_PATH }}
        run: |
          archivePath=build/$SCHEME.xcarchive
          exportPath=build/$SCHEME

          echo "::set-output name=IPA_FILE::$exportPath/$SCHEME.ipa"
          
          exportOptionsPlist=$RUNNER_TEMP/export.plist
          cat > $exportOptionsPlist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
          </dict>
          </plist>
          EOL
          
          xcodebuild \
            -exportArchive \
            -archivePath "$archivePath" \
            -exportPath "$exportPath" \
            -exportOptionsPlist "$exportOptionsPlist" \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            -authenticationKeyID $API_KEY_ID \
            -authenticationKeyIssuerID $ISSUER_ID | xcpretty && exit ${PIPESTATUS[0]} 

      - name: Upload app to TestFlight (iOS)
        env:
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          IPA_FILE: ${{ steps.archive-ios.outputs.IPA_FILE }}
        run: |
          xcrun altool \
            --upload-app \
            --file $IPA_FILE \
            --type ios \
            --apiKey $API_KEY_ID \
            --apiIssuer $ISSUER_ID

      - name: Build (tvOS)
        id: build-tvos
        env:
          SCHEME: ${{ 'SwiftyTV' }}
        run: |
          archivePath=build/$SCHEME.xcarchive

          echo "::set-output name=SCHEME::$SCHEME"

          xcodebuild clean build archive \
            -scheme "$SCHEME" \
            -archivePath "$archivePath" \
            ENABLE_BITCODE=YES | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive (tvOS)
        id: archive-tvos
        env:
          SCHEME: ${{ steps.build-tvos.outputs.SCHEME }}
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          AUTH_KEY_PATH: ${{ steps.appstore-private-key.outputs.AUTH_KEY_PATH }}
        run: |
          archivePath=build/$SCHEME.xcarchive
          exportPath=build/$SCHEME

          echo "::set-output name=IPA_FILE::$exportPath/$SCHEME.ipa"
          
          exportOptionsPlist=$RUNNER_TEMP/export.plist
          cat > $exportOptionsPlist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
          </dict>
          </plist>
          EOL
          
          xcodebuild \
            -exportArchive \
            -archivePath "$archivePath" \
            -exportPath "$exportPath" \
            -exportOptionsPlist "$exportOptionsPlist" \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$AUTH_KEY_PATH" \
            -authenticationKeyID $API_KEY_ID \
            -authenticationKeyIssuerID $ISSUER_ID | xcpretty && exit ${PIPESTATUS[0]} 

      - name: Upload app to TestFlight (tvOS)
        env:
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          IPA_FILE: ${{ steps.archive-tvos.outputs.IPA_FILE }}
        run: |
          xcrun altool \
            --upload-app \
            --file $IPA_FILE \
            --type tvos \
            --apiKey $API_KEY_ID \
            --apiIssuer $ISSUER_ID

